<a href="https://colab.research.google.com/github/francomanca93/analisis-de-datos/blob/comienzo/1-Comenzando-con-pandas/1_Configurando_Google.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Configurando Google Colab

### Google colab

Google te brinda una maquina virtual con 100 GB y 12 GB de RAM, estas especificaciones te permiten ejecutar codigos mas complejos en la nube. Ademas colab viene con la mayoria de librerias para el uso en ciencia de datos y machine learning.

Ventajas:

* Mejor poder computacional. Tienes acceso a GPU’s que generalmente son caros.
* No tienes que configurar las GPU’s, pues ya vienen preconfiguradas. Inclusive puedes usar TPU’s
* No tienes la dificultad de instalar librerías.
* Si quieres usar la versión de paga, no es tan caro como Google Cloud, AWS, etc.

Desventajas:

* Solo te dan 12 horas en la versión gratuita y 24 horas en la versión de paga.


## Cuentas básicas para probar Google Colab

In [1]:
10+3

13

In [2]:
2*3

6

In [3]:
2**3

8

## Definimos variables en Google Colab

In [5]:
x = 12
x

12

In [6]:
y = 15

In [7]:
x + y

27

In [8]:
'Hola mundo de Colab'

'Hola mundo de Colab'

In [9]:
x = 'Hola'
y = 'mundo'
x + ' ' + y

'Hola mundo'

## Definiendo y jugando con listas en Google Colab

In [10]:
[1,2,3,4,5,6]

[1, 2, 3, 4, 5, 6]

In [11]:
[1,2,3] + [2,4,6]

[1, 2, 3, 2, 4, 6]

In [12]:
lista = [1,2,3,4,5]

In [13]:
lista[0]

1

In [14]:
lista[2]

3

In [15]:
lista[-1]

5

In [16]:
[1,2,3,4,5] + [10]

[1, 2, 3, 4, 5, 10]

## Importancia de Numpy para manipular datos

In [17]:
import numpy as np

In [18]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [19]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [20]:
np.array([1,2,3,4,5]).shape

(5,)

In [22]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [23]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [25]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [26]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3